### ISSUE TITLE
Note Color Changing Keeps Randomly Responding With "Null Object Reference"

### ISSUE THREAD

**Issue by NullifiedGitHub** [VideoBotYT/Universe-Engine#9]
### Describe your bug here.

I just want to make my note colors yellow but an error keeps saying "Null Object Reference" at the most random times.
![notecolorerror](https://github.com/user-attachments/assets/32895f8d-8b72-4365-a4c5-40d6df1f60f0)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is normal Universe Engine.

**Comment by VideoBotYT** [comment]
known bug update coming very soon with the fix

**Comment by NullifiedGitHub** [comment]
> known bug update coming very soon with the fix

Ok, thank you. It's happening mostly by clicking somewhere with no hitbox, or a blank area. It's only that specific menu.

**Comment by VideoBotYT** [comment]
> > known bug update coming very soon with the fix
> 
> Ok, thank you. It's happening mostly by clicking somewhere with no hitbox, or a blank area. It's only that specific menu.

again known issue it's been there since first release of the engine. this is why it happens:

in the menus code i forgot to remove an if statement that checks if u click on a pixel note or not so that means that if u click somewhere random on the menu the menu gets confused and crashes the game with a nice null object

**Comment by uwenalil** [comment]
https://github.com/VideoBotYT/Universe-Engine/issues/4
heres what he meant btw
